### ISSUE TITLE
Extract predicted conditional distribution parameters

### ISSUE THREAD

**Issue by ummel** [Akai01/ngboost#1]
Hi Resul -- Thanks for working to provide an R interface to NGBoost. I installed it and worked through the README example.

Question: How can I extract the predicted conditional distribution parameters? For example, building off of the Boston dataset example:

```
model <- NGBRegression$new(Dist = Dist("Normal"),
                           Base = sklearner(),
                           Score = Scores("LogScore"),
                           natural_gradient = TRUE,
                           n_estimators = 600,
                           learning_rate = 0.002,
                           minibatch_frac = 0.8,
                           col_sample = 0.9,
                           verbose = TRUE,
                           verbose_eval = 100,
                           tol = 1e-5)

model$fit(X = x_train, Y = y_train, X_val = x_test, Y_val = y_test)
```
Conditional means predict just fine:
`model$predict(x_test) %>% head()`

But I would expect a two-column matrix or data frame for the conditional parameters:
`model$pred_dist(x_test)`

Instead, it returns a Python built-in object. How can I extract that to R?

**Comment by Akai01** [comment]
For now, I would suggest the following way, but I would like to make this easier for users.

```
dist <- model$pred_dist(x_test)

dist$dist$interval(alpha = 0.9) # alpha  should be in (0,1)

dist$dist$mean() #for the mean. It is same as  model$predict(x_test)

dist$dist$mean() == model$predict(x_test)
```

I hope this solves the problem

**Comment by ummel** [comment]
Thanks. I wasn't aware of the additional functions within 'dist'. Can do the following to extract the conditional parameters:

```
dist <- model$pred_dist(x_test)
pred <- data.frame(dist$params)
```

**Comment by Akai01** [comment]
pred_dist method now returns a NgbDist object

See example :

```
library(ngboost)

data(Boston, package = "MASS")

dta <- rsample::initial_split(Boston)

train <- rsample::training(dta)

test <- rsample::testing(dta)


x_train = train[,1:13]
y_train = train[,14]

x_test = test[,1:13]
y_test = test[,14]


model <- NGBRegression$new(Dist = Dist("Exponential"),
                           Base = sklearner(),
                           Score = Scores("MLE"),
                           natural_gradient =TRUE,
                           n_estimators = 600,
                           learning_rate = 0.002,
                           minibatch_frac = 0.8,
                           col_sample = 0.9,
                           verbose = TRUE,
                           verbose_eval = 100,
                           tol = 1e-5)

model$fit(X = x_train, Y = y_train, X_val = x_test, Y_val = y_test)

model$feature_importances()

model$plot_feature_importance()

model$predict(x_test)%>%head()

distt <- model$pred_dist(x_test)

# Please see the documentation of the NgbDist class for available methods

?NgbDist

# methods

distt$cdf(quantiles = .1)
distt$entropy()
distt$interval(confidence = .9)
distt$isf(q = 0.1)
distt$logcdf(0.2)
distt$logpdf(quantiles = 0.2)
distt$logsf(quantiles = 1)
distt$mean()
distt$median()
distt$median()
distt$pdf(quantiles = 0.1)
distt$ppf(0.1)
distt$rvs()
distt$sf(0.1)
distt$std()
distt$var()

```

**Comment by frequena** [comment]
Thank you very much @Akai01 for working on the R port of the NGBoost package. 

I'm interested in extracting the predicted conditional distribution parameters of the classification task model that is available on the repository README. Unfortunately, no matter the function I apply (e.g. mean, median, std...) I always get the same error: 

`Erreur dans py_get_attr_impl(x, name, silent) : 
  AttributeError: 'Categorical' object has no attribute 'mean'`

Thank you again!!

**Comment by Akai01** [comment]
> Thank you very much @Akai01 for working on the R port of the NGBoost package.
> 
> I'm interested in extracting the predicted conditional distribution parameters of the classification task model that is available on the repository README. Unfortunately, no matter the function I apply (e.g. mean, median, std...) I always get the same error:
> 
> `Erreur dans py_get_attr_impl(x, name, silent) : AttributeError: 'Categorical' object has no attribute 'mean'`
> 
> Thank you again!!

I created a new issue. see https://github.com/Akai01/ngboost/issues/2
