### ISSUE TITLE
error in installing the package

### ISSUE THREAD

**Issue by jijo7** [Akai01/ngboost#3]
Hi. Thanks for sharing ngboost. I tried to install it but the followings were reported:
```
> install.packages("ngboost")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/ihc/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ngboost’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> 
> devtools::install_github("Akai01/ngboost")
Error in loadNamespace(x) : there is no package called ‘devtools’
```

**Comment by Akai01** [comment]
The package is not on Cran yet; hence `install.packages("ngboost")` will not work. 

To install the GitHub version, please first run `install.packages("devtools")`, then re-start your R session, then run `devtools::install_github("Akai01/ngboost")`. If you are using windows OS, first install Rtools and restart your R, then please try again.

**Comment by jijo7** [comment]
@Akai01 Thanks. I did the steps but now this error is reported:
```
"C:/Users/ihc/AppData/Local/r-miniconda/condabin/conda.bat" "create" "--yes" "--prefix" "C:/Users/ihc/AppData/Local/r-miniconda/envs/r-reticulate" "python=3.8" "numpy" "--quiet" "-c" "conda-forge"
Collecting package metadata (current_repodata.json): ...working... failed

CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to
download and install packages.

Exception: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```

I also did [these instructions](https://thesecmaster.com/procedure-to-install-openssl-on-the-windows-platform/#:~:text=Go%20to%20Advanced%20%3E%20Environment%20Variable,Set%20OPENSSL_CONF%20and%20Path%20variables.&text=Open%20the%20command%20prompt%20using,configured%20on%20your%20Windows%20machine.) but again the same error is reported. Could you please let me know how to resolve it? Thanks in advance.

**Comment by Akai01** [comment]
@jijo7 I think you are on a network proxy, and that blocks you to install `miniconda.`
Please check with this `reticulate::conda_list()` whether you have `miniconda` installed on your machine, you should see something like this `/r-miniconda/bin/python`. If `miniconda` is not installed on your machine, run this `reticulate::install_miniconda()`. If it is still not working, you will not be able to use the package because system requirements are failing. Try to install `miniconda` with `reticulate::install_miniconda()`

**Comment by jijo7** [comment]
@Akai01 Thanks for your time and patience.  So sorry for this inconvenience.  It seems `miniconda` is installed but it reports:

```
[Workspace loaded from ~/.RData]

> reticulate::conda_list()
            name                                                     python
1           base     C:\\Users\\ihc\\AppData\\Local\\r-miniconda/python.exe
2      anaconda3                       C:\\Users\\ihc\\anaconda3/python.exe
3 pythonProject1 C:\\Users\\ihc\\anaconda3\\envs\\pythonProject1/python.exe
4 pythonProject4 C:\\Users\\ihc\\anaconda3\\envs\\pythonProject4/python.exe
5       untitled       C:\\Users\\ihc\\anaconda3\\envs\\untitled/python.exe
> devtools::install_github("Akai01/ngboost")
Skipping install of 'ngboost' from a github remote, the SHA1 (afa4dea4) has not changed since last install.
  Use `force = TRUE` to force installation
> install_github("ngboost", force=TRUE)
Error in install_github("ngboost", force = TRUE) : 
  could not find function "install_github"
> 
```
